/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesProtocolsRouteImport } from './routes/courses.protocols'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesProtocolsRoute = CoursesProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => CoursesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/demo': typeof DemoRoute
  '/placements': typeof PlacementsRoute
  '/playlists': typeof PlaylistsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/protocols': typeof CoursesProtocolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/demo': typeof DemoRoute
  '/placements': typeof PlacementsRoute
  '/playlists': typeof PlaylistsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/protocols': typeof CoursesProtocolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/demo': typeof DemoRoute
  '/placements': typeof PlacementsRoute
  '/playlists': typeof PlaylistsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/protocols': typeof CoursesProtocolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alumni'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/demo'
    | '/placements'
    | '/playlists'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/blog/$slug'
    | '/courses/protocols'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alumni'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/demo'
    | '/placements'
    | '/playlists'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/blog/$slug'
    | '/courses/protocols'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alumni'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/demo'
    | '/placements'
    | '/playlists'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/blog/$slug'
    | '/courses/protocols'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlumniRoute: typeof AlumniRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DemoRoute: typeof DemoRoute
  PlacementsRoute: typeof PlacementsRoute
  PlaylistsRoute: typeof PlaylistsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/protocols': {
      id: '/courses/protocols'
      path: '/protocols'
      fullPath: '/courses/protocols'
      preLoaderRoute: typeof CoursesProtocolsRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CoursesRouteChildren {
  CoursesProtocolsRoute: typeof CoursesProtocolsRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesProtocolsRoute: CoursesProtocolsRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlumniRoute: AlumniRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DemoRoute: DemoRoute,
  PlacementsRoute: PlacementsRoute,
  PlaylistsRoute: PlaylistsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
